### DISCUSSION TITLE
Posición HTML / CSS

### DISCUSSION THREAD

**Discussion by HoyosQ** [enflujo/.github#25] [Preguntas] [answered]
Estoy teniendo algunos problemas intentando ubicar ciertos elementos dentro de mi codigo en algunas posiciones de la pagina. Existe alguna herramienta que me ayude a entender mejor las propriedades que definen esto?  Si quieren puedo compartir el codigo y una imagen de como se ve.

**Comment by HoyosQ** [comment]
Codigo CSS
```CSS
body{
  position:relative;
  background-color:#3a5a40;
  padding:center;
  margin-left: auto;
  margin-right: auto;
  width: 15em;
}

#titulo{
  color:#ffbf69;
}

#palabras{
  color: #dddf00;
  opacity:50%;
  z-index:-1;
}

#cuadro{
  margin-left:-8em;
  border:25px;
  border-color:#eec170;
  border-style:groove;
  width:25em;
  height:70vh;
  background-image:url("https://cdn.glitch.global/54da8c06-5f33-462e-8d18-fca122f95c1d/fondo1.jpg?v=1678471721776");
  background-repeat:no-repeat;
  background-size: cover;
}



#boton{
  background-color:#606c38;
  color:#fefae0;
  margin-top:2em;
  margin-left: auto;
  margin-right: auto;
  width: 15em;

}
footer{
  width:15em;
  position:absolute;
  bottom:-1em;
}

#verde{
  width:15em;
  height:15em;
  display:;
}
```
Codigo HTML
```HTML
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="/favicon.ico" sizes="any" />
    <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
    <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
    <link rel="manifest" href="/sitio.webmanifest" />
    <title>..:: Yo Latino ::..</title>
    <link rel="stylesheet" href="/style.css" />
    <script src="/script.js" defer></script>
  </head>

  <body>
    <h1 id="titulo">Mi Yo Latino</h1>
    <p id="palabras">
    
    </p>
    <div id="cuadro">
      <img id="latino1" src=","/>
      <img id="latino2" src=","/>
      <img id="latino3" src=","/>
    </div>
    
    <button id="boton">Latinízame</button>
  </body>
  <footer>
      <img id="verde" src="https://cdn.glitch.global/54da8c06-5f33-462e-8d18-fca122f95c1d/aprovado.png" />
    </footer>
</html>

```
![image](https://user-images.githubusercontent.com/89080958/224509837-87d1aa7d-3c36-4895-bd00-6f70aa8e0b05.png)

Quiero que la imagen de Omar se vea siempre abajo a la izquierda.
